#for configuration start: roslaunch tod_input_devices tod_input_devices.launch ConfigMode:=true
Type: "Usb" 


ButtonConfig:
  "IndicatorLeft": 5                 #left shift paddle
  "IndicatorRight": 4                #right shift paddle
  "EmergencyLight": 23               # <-
  "IncreaseSpeed": 6                 #left shift paddle
  "DecreaseSpeed": 7                 #right shift paddle 
  "Park": 2                          #button circle
  "Reverse": 0                       #button x
  "Neutral": 1                       #button rectangular
  "Drive": 3                         #button triangle
  "Remote": 24                       #PS button
  "VideoStream": 8                   #SHARE button
  "AVMStream": 9                     #OPTION button
  

AxisConfig:
  "Steering": 0
  "Throttle": 2
  "Brake": 3

InputDeviceHasSeparateBrakingAxis: true #If False: AxisRange/Brake is ignored (see below)

InvertAxis:
  "Steering": false 
  "Throttle": true
  "Brake": true

# Jostick Correction only supported for USB - Optional
Correction: "6,\
  1,0,32767,32767,16384,16384,\
  1,0,127,127,4227330,4227330,\
  1,0,127,127,4227330,4227330,\
  1,0,127,127,4227330,4227330,\
  1,0,0,0,536870912,536870912,\
  1,0,0,0,536870912,536870912"


# Correction Parameters according to jscal
# n,\
# a,b,C0,C1,C2,C3\
# ....
#
# n:  Number of axis, should correspond to the following lines
# a:  Type 1 = "broken line"
# b:  Precision
# C0: Start of Deadzone
# C1: End of Deadzone
# C2: Negative Gradient
# C3: Positive Gradient