uint32 psid_ext
uint8 cast_mode
uint32 src_id
uint32 dst_id

uint16 eDeviceType
uint16 eTeleCommType
uint32 unDeviceId
uint16 eServiceId
uint16 eActionType
uint16 eRegionId
uint16 ePayloadType
uint16 eCommId
uint16 usDbVer
uint16 usHwVer
uint16 usSwVer

---

bool success
string message